### ISSUE TITLE
euphony-listener README.md 채우기

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony-listener#4]
@euphony-io/eutopia 팀에 배정드리는 첫번째 이슈입니다.

https://github.com/pytorch/android-demo-app/tree/master/ASLRecognition
https://github.com/pytorch/android-demo-app/tree/master/TorchVideo

위 보시면 다양한 데모 앱에 대하여 README.md가 업데이트 되어 있어요.
여러분이 공식 euphony-listener 앱의 README.md가 현재 부재하니 업데이트 해보면 좋을 것 같아요.

한국어/영어 버전 각각 만들어주시면 좋을 것 같고 영어를 기본 컨텐츠로 잡으면 좋을 것 같습니다.

우선은 여기 issue 페이지를 통해서 커뮤니케이션을 하면서 전체 구성을 완성해보시구요.
내용도 어떻게 쓸지 각자 커뮤니케이션을 여기서 남겨가면서 작성해보면 좋겠습니다.

PR은 이번주 토요일 이후에 진행해보시도록 할게요 :)

**Comment by eunzinn** [comment]
헉 잘못 눌렀어요 ㅠㅠ 죄송합니다!..

**Comment by kuro11pow2** [comment]
멘토님이 올려주신 링크를 살펴봤는데 다음과 같은 구성으로 되어있었습니다.

* Introduction
* Prerequisites
* Quick Start

저희도 이 구성으로 가보면 어떨까요? 
[euphony-io/euphony](https://github.com/euphony-io/euphony)의 README 상단 형식을 따서 Introduction은 생략해도 좋을 것 같습니다.

**Comment by eunzinn** [comment]
좋아요! euphony Introduction은 생략하고 euphony-listener의 기능을 간략하게 적는게 좋을 것 같아요!

**Comment by designe** [comment]
ㅎㅎ 잘하고 있네요. 최대한 issues 만을 통해 소통하는 모습을 여기에 보여주시면 좋을 것 같습니다! markdown 과하게 이것저것 써보시구요!

**Comment by kmsaidev** [comment]
저도 좋아요!! 메일 계정이 혼동되어서 지금 봤습니다. Quick start 부분에서 멘토님이 올려주신 링크의 예시처럼 스크린샷 이미지를 통해 실행 결과를 보여주는 게 좋을 것 같아요ㅎㅎ!!

**Comment by judemin** [comment]
이전에 각자 테스트 했을때는 결과가 제대로 나오지 않았지만 8/11 회의때 다 같이 다시 빌드하고 수행해보니 결과가 제대로 나왔습니다. 하지만 test를 송신하고 수신했을 때는 오차없이 데이터가 도착하였지만 tmp123으로 다시 테스트 했을때는 tMp1D과 같이 온전하지 못한 데이터가 수신되어 라이브러리에 어떤 문제가 있을지에 대해 얘기해보았습니다.

**Comment by kuro11pow2** [comment]
android studio에서 빌드해서 테스트해봤는데요, [speaker](https://dev.jbear.co/euphony/)의 기본 값인 hello, euphony는 인식이 되지 않는데, hello world나 test는 금방 인식이 되었습니다.

**Comment by judemin** [comment]
README.md 수정하는거 저희 역할분담 어떻게 할까요??

**Comment by kmsaidev** [comment]
제가 다른 분들 쓰시는 것과 기본 내용 번역 하겠습니다!!

**Comment by judemin** [comment]
> 제가 다른 분들 쓰시는 것과 기본 내용 번역 하겠습니다!!

근데 그거 양이 좀 많을거 같던데 저랑 앞뒤 나눠서 하시면 어떨까요?

**Comment by kuro11pow2** [comment]
> README.md 수정하는거 저희 역할분담 어떻게 할까요??

저는 Quick Start 항목 작성해보겠습니다!

**Comment by kmsaidev** [comment]
> > 제가 다른 분들 쓰시는 것과 기본 내용 번역 하겠습니다!!
> 
> 
> 
> 근데 그거 양이 좀 많을거 같던데 저랑 앞뒤 나눠서 하시면 어떨까요?

넵 좋아요!!☺️☺️

**Comment by kmsaidev** [comment]
# euphony-listener
Euphony Listener / Euphony Library Demo Solution
Acoustic Data Telecommunication Library. This is for Android version.
Euphony provides a handiness library designed to communicate with other devices(android and web) using mic and recorder.
Official Facebook Page : https://www.facebook.com/euphonyproject
Official Library Site : https://dev.jbear.co/euphony
## Prerequisite
build.gradle in app module
```java
dependencies {
    implementation 'euphony.lib:euphony:0.7.1.6'
}
```
AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```
## Quick Start


### 1. Repository clone (저장소 클론)

```bash
$ git clone https://github.com/euphony-io/euphony-listener.git
```

![clone](https://user-images.githubusercontent.com/47289893/128968369-e30bfc36-3c57-418d-b3b2-b8976436493b.png)


### 2. Open in Android Studio (안드로이드 스튜디오에서 열기)

Find the path of the cloned project and open it.  
clone한 프로젝트의 경로를 찾아서 열어준다.

![open](https://user-images.githubusercontent.com/47289893/128968509-21778091-1c48-432d-8c68-856d89c59a07.png)

Press the 'Trust Project' button.  
Trust Project 버튼을 누른다.

![trust](https://user-images.githubusercontent.com/47289893/128968544-78756386-1740-43e7-9f27-78f9322307f8.png)


### 3. JDK settings (JDK 설정)

JDK location error may occur when opening the file for the first time.  
처음 열 때 JDK location error가 발생할 수 있다.

![set jdk-1](https://user-images.githubusercontent.com/47289893/128968605-e73af820-0ae7-4e8c-997a-1c1cdbef7129.png)

Click 'Change JDK location' to specify Gradle JDK.  
Change JDK location을 클릭하여 Gradle JDK를 지정한다.

![set jdk-2](https://user-images.githubusercontent.com/47289893/128968614-0988ac95-1672-411d-8e9e-336503be69cd.png)

When you reopen the project, the build starts.  
프로젝트를 다시 열면 build가 시작된다.

![build](https://user-images.githubusercontent.com/47289893/128968741-00b1cd80-a9f7-4481-bd1a-ff388141080f.png)



### 4. Connect the device (디바이스 연결)

By default, there is no device.  
기본적으로 디바이스가 없다.

![no device](https://user-images.githubusercontent.com/47289893/128968845-d0868890-cb57-4721-a956-857b871e7393.png)

It is automatically recognized when devices with developer mode are connected.  
개발자 모드가 활성화된 디바이스를 연결하면 자동으로 인식된다.

![yes device](https://user-images.githubusercontent.com/47289893/128968864-35b7ae72-6fb8-4bb2-8706-1ec2257faf73.png)



### 5. Test (테스트)

Operate 'euphony-listener' app on the connected device.  
연결된 디바이스에서 euphony-listener를 동작시킨다.

![run](https://user-images.githubusercontent.com/47289893/128968893-cca8c520-4dcc-41e7-9e04-9d4849143176.png)

![run-build](https://user-images.githubusercontent.com/47289893/128969518-043e50ae-aa45-4d0a-b145-9e7d1176353c.png)

#### Speaker

Speaker demo is available at [here](https://dev.jbear.co/euphony/). Enter short text and press the 'broadcast' button.  
[여기](https://dev.jbear.co/euphony/)에서 Speaker demo를 사용할 수 있다. 짧은 텍스트를 입력하고 broadcast 버튼을 누른다.

![speaker](https://user-images.githubusercontent.com/47289893/128968935-b4cd781a-5de0-42cf-a01a-ec87a47f77b6.png)


#### Listener

When the 'LISTEN' button is pressed, recognition begins.  
LISTEN 버튼을 누르면 인식이 시작된다.

![device](https://user-images.githubusercontent.com/47289893/128969127-1b7847ec-43c7-42cb-8b6b-a6602f51db7f.png)

#### Log

![logcat](https://user-images.githubusercontent.com/47289893/128969052-3b70b562-f4ce-4ba6-98e5-d9be4096ab76.png)


## Euphony Listener is very easy to use (Euphony Listener는 사용하기 매우 쉽습니다.)
```java
EuRxManager mRxManager = new EuRxManager();
mRxManager.setAcousticSensor(new AcousticSensor() {
@Override
    public void notify(String letters) {
        //when data is received
    }
});
mRxManager.listen();  //Listening Start
// if you want to finish listening, call the finish();
// mRxManager.finish();
```
## Architecture (아키텍처)
euphony architecture
## Contributing (기여)
Changes and improvements are more than welcome! Feel Free to fork and open a pull request. Please make your changes in a specific branch and request to pull into master.  
변화와 개선을 환영합니다! 자유롭게 fork와 PR하세요. 당신의 변경사항을 특정한 branch에 commit해주시고 master branch로 PR해주세요.
## License
Euphony is licensed under the Apache 2.0 license. (https://github.com/designe/Euphony/blob/master/LICENSE)  
Euphony는 Apache 2.0 license에 따라 라이센스가 부여됩니다.

**Comment by kmsaidev** [comment]
준규님이 만들어주신 quick start에 제가 원래 하기로 했던 부분까지 번역한 내용입니다.

**Comment by judemin** [comment]
# euphony-listener
Euphony Listener / Euphony Library Demo Solution </br>
Euphony 리스너 / Euphony 라이브러리를 활용한 데모 프로그램 </br>

Acoustic Data Telecommunication Library. This is for Android version. </br>
Euphony provides a handiness library designed to communicate with other devices(android and web) using mic and recorder. </br>
해당 음파 데이터 통신 라이브러리, Euphony의 버전은 안드로이드를 위한 버전입니다. </br>
Euphony는 마이크와 녹음기를 활용하여 다른 단말기(안드로이드, 웹)들과 통신하기 위해 디자인 된 무선 라이브러리를 제공합니다.  </br>

Official Facebook Page : https://www.facebook.com/euphonyproject </br>
Official Library Site : https://dev.jbear.co/euphony </br>
공식 페이스북 페이지 : https://www.facebook.com/euphonyproject </br>
공식 라이브러리 주소 : https://dev.jbear.co/euphony </br>

## Prerequisite (라이브러리 설치)
build.gradle in app module </br>
앱 단위의 build.gradle
```java
dependencies {
    implementation 'euphony.lib:euphony:0.7.1.6'
}
```
AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```

은진님 파트 전까지 번역한 내용입니다!

**Comment by eunzinn** [comment]
# euphony-listener
Euphony Listener / Euphony Library Demo Solution

## Introduction (소개)
'Euphony-Listener' receives and recognizes data through sound waves from 'Speaker'.   
The frequency occurs when the speaker sends data. The Listen button is pressed, 'Listener' recognizes the data and you can check the results.  
It only works on android. 

Euphony-Listener는 Speaker로부터 음파를 통해 데이터를 받아 인식하는 기능을 합니다.  
스피커가 데이터를 보낼 때 주파수가 발생하게 되는데, Listen 버튼을 누르면 Listener가 데이터를 인식하여 그 결과를 확인할 수 있습니다.  
android에서만 동작을 합니다.  

Introduction 작성한 내용 입니다!

**Comment by judemin** [comment]
Co-Author 활용해서 commit하고 master branch에 PR까지 완료했습니다!

**Comment by judemin** [comment]
readme 이외의 파일들은 빌드할 때 gradle이나 기타 세팅 파일과 저희 저번에 테스트 할 때 Log 추가했다 지웠던 파일이었어서 Co-Author 테스트 할 때 커밋했습니다
